<h1 style="font-size:2.5em; text-align:center">R√©soudre une enqu√™te gr√¢ce au langage SQL</h1>

---

<div class="alert alert-block alert-info" style="border-left:10px solid #000066;">
    
**<span style="font-size:2em">üìñ</span> Si c'est la premi√®re fois que vous utilisez un document comme celui-ci voici quelques informations n√©cessaires** :

- Il s'agit d'un *notebook* (ou carnet de notes) qui permet de m√©langer du texte mais aussi d'√©crire et ex√©cuter du code √©crit dans un langage informatique (ici dans le langage SQL)
- Le notebook est une succession de *cellules* de texte et de code (les cellules de code sont celles sur fond gris avec `Entr√©e[ ]` √©crit sur la gauche)
- Pour ex√©cuter le code √©crit dans une cellule (de code), il suffit de la s√©lectionner en cliquant dessus puis de cliquer sur le bouton <button class='fa fa-step-forward'> Ex√©cuter</button> situ√© dans la barre de menu en haut de page. Si le code ex√©cut√© produit une sortie vous la verrez directement en-dessous.
- Si vous double-cliquez malencontreusement sur une cellule de texte vous verrez appara√Ætre le code (Markdown ou HTML) permettant d'afficher cette cellule, il suffit de cliquer sur le bouton <button class='fa fa-step-forward'> Ex√©cuter</button> pour revenir √† la normal
    
</div>

Le **langage SQL** (Structured Query Language, soit *langage de requ√™te structur√©e*) est utilis√© pour rechercher, ajouter, modifier ou supprimer des donn√©es dans une base de donn√©es. C'est une langage tr√®s proche de la langue naturelle.

On vous propose dans la suite de cette √©nigme de comprendre les rudiments de ce langage pour ensuite l'utiliser pour r√©soudre une enqu√™te afin de trouver le suspect qui a commis un d√©lit de fuite apr√®s un accrochage en voiture.

<img alt="illustration" src="https://infonigma.eu.pythonanywhere.com/static/assets/accident.png" width="300">

# La base de donn√©es utilis√©e

On dispose d'informations sur les habitants d'une ville ainsi que sur le permis de conduire de ces derniers. Ces informations sont stock√©es dans une base de donn√©es contenant deux tables :

- La table `Habitants` qui contient des informations sur les habitants d'une ville dont voici un extrait :

| id | nom | num_permis | num_rue |	rue |
| --- | --- | --- | --- | --- |
| 1 | Bernadette Le Grondin | 386143510615 | 2 |	rue de Leli√®vre |
| 2 | Benjamin Ramos | 458982973468	| 11 | rue Alan Turing |
| 3 | Olivie Brun |	347646845156 | 498 | rue de Seguin |
| 4	| Michelle Guillaume | 632967944559 | 38 | rue de Seguin |
| 5 | Matthieu Rey | 898755649031 | 25 | chemin Dumont |
| ... | ... | ... | ... | ... |

Voici la description des diff√©rentes colonnes :

- `id` : l'identifiant de l'habitant (un *entier*) 
- `nom` : le pr√©nom et le nom de l'habitant (une *cha√Æne de caract√®res*)
- `num_permis` : le num√©ro de permis de l'habitant (un *entier*)
- `num_rue` : le num√©ro de rue de l'habitant (un *entier*)
- `rue` : le nom de la rue de l'habitant (une *cha√Æne de caract√®res*)

- La table `Permis` qui contient des informations correspondant au permis de conduire des habitants de cette ville, en voici un extrait :

| num_permis | genre | age | yeux |	cheveux | immatriculation | marque |
| --- | --- | --- | --- | --- | --- | --- |
| 100853173735	| M	| 30 | noisette	| noir	| DE-690-AQ	| Citroen |
| 101741559305	| M	| 68 | marron | blanc | DN-548-GM | Peugeot |
| 103042877950	| F	| 38 | noisette | blanc| DV-516-EU | BMW |
| 104304445069	| M	| 53 | marron | auburn | GE-808-SI | Suzuki |
| 104610705500	| F | 51 | vert | ch√¢tain | BY-232-YR | Skoda |
| ... | ... | ... | ... | ... | ... | ... |

Voici la description des diff√©rentes colonnes :

- `num_permis` : le num√©ro de permis de l'habitant (un *entier*)
- `genre` : le sexe du conducteur (une *cha√Æne de caract√®res*) 
- `age` : l'√¢ge du conducteur (un *entier*)
- `yeux` : la couleur des yeux du conducteur (une *cha√Æne de caract√®res*) 
- `cheveux` : la couleur des cheveux du conducteur (une *cha√Æne de caract√®res*) 
- `immatriculation` : le num√©ro de plaque d'immatriculation de la voiture du conducteur (une *cha√Æne de caract√®res*)
- `marque` : la marque de la voiture du conducteur (une *cha√Æne de caract√®res*)

# Le langage SQL

Le langage SQL permet d'√©crire des requ√™tes pour obtenir des informations pr√©sentes dans la base de donn√©es. C'est un langage assez proche de la langue naturelle comme vous allez le voir avec les exemples suivants qui pr√©sentent les rudiments du langage SQL.

Les requ√™tes que vous allez √©crire permettent de r√©cup√©rer dans une table, toutes les lignes qui correspondent √† la requ√™te.

## Exemple 1

On veut ici r√©cup√©rer toutes les informations pr√©sentes dans la table `Habitants`, autrement dit r√©cup√©rer toutes les informations (= les valeurs de toutes les colonnes) de toutes les lignes de la table. On peut √©crire cela de la fa√ßon suivante en langue naturelle :

<pre><code class="cm-s-ipython language-sql"><span class="cm-keyword">SELECTIONNER</span> <span class="cm-operator">TOUTES LES COLONNES</span>
<span class="cm-keyword">DANS</span> Habitants
</code></pre>

Dans le langage SQL on traduit cette requ√™te de la fa√ßon suivante (*pensez √† ex√©cuter la cellule suivante pour voir le r√©sultat*) :

In [ ]:
SELECT *
FROM Habitants

><span style="font-size:1.5em">üì£</span> C'est l'√©toile `*` apr√®s `SELECT` qui signifie que toutes les colonnes doivent √™tre affich√©es dans les r√©sultats.

On peut faire de m√™me avec la table `Permis` (*pensez √† ex√©cuter la cellule suivante pour voir le r√©sultat*) :

In [ ]:
SELECT *
FROM Permis

## Exemple 2

On veut maintenant r√©cup√©rer toutes les informations (= les valeurs de toutes les colonnes) de la table `Permis` des personnes ayant 40 ans.

On peut √©crire cela de la fa√ßon suivant en langue naturelle :

<pre><code class="cm-s-ipython language-sql"><span class="cm-keyword">SELECTIONNER</span> <span class="cm-operator">TOUTES LES COLONNES</span>
<span class="cm-keyword">DANS</span> Permis
<span class="cm-keyword">TEL QUE</span> age <span class="cm-operator">=</span> <span class="cm-number">40</span>
</code></pre>

Dans le langage SQL on traduit cette requ√™te de la fa√ßon suivante (*pensez √† ex√©cuter la cellule suivante pour voir le r√©sultat*) :

In [ ]:
SELECT *
FROM Permis
WHERE age = 40

En suivant le m√™me principe, la requ√™te suivante permet de r√©cup√©rer les informations sur tous les habitants de la rue de Seguin :

In [ ]:
SELECT *
FROM Habitants
WHERE rue = "rue de Seguin"

><span style="font-size:1.5em">üì£</span> **Important** : on a mis des guillemets autour de "rue de Seguin" car il s'agit d'une cha√Æne de caract√®res. Il n'y en a pas autour du 40 dans la requ√™te pr√©c√©dente car l'√¢ge est un entier. Il faudra toujours proc√©der ainsi, le type des donn√©es (entier ou cha√Æne de caract√®res) est donn√© dans les descriptions des deux tables au d√©part : [voir ici](#La-base-de-donn√©es-utilis√©e).

## Exemple 3

On veut maintenant r√©cup√©rer toutes les informations (= les valeurs de toutes les colonnes) de la table `Permis` **des filles** ayant 30 ans.

On peut rajouter la condition sur le genre de la fa√ßon suivante en langue naturelle :

<pre><code class="cm-s-ipython language-sql"><span class="cm-keyword">SELECTIONNER</span> <span class="cm-operator">TOUTES LES COLONNES</span>
<span class="cm-keyword">DANS</span> Permis
<span class="cm-keyword">TEL QUE</span> age <span class="cm-operator">=</span> <span class="cm-number">40</span> <span class="cm-keyword">ET</span> genre <span class="cm-operator">=</span> <span class="cm-string">"F"</span>
</code></pre>

Dans le langage SQL on traduit cette requ√™te de la fa√ßon suivante (*pensez √† ex√©cuter la cellule suivante pour voir le r√©sultat*) :

In [ ]:
SELECT *
FROM Permis
WHERE age = 40 AND genre = "F"

><span style="font-size:1.5em">üì£</span> Remarquez les guillemets du "F" car il s'agit d'une cha√Æne de caract√®res et l'absence de guillemets autour du 40 car il s'agit d'un entier.

## Exemple 4 (pas n√©cessaire pour cette √©nigme)

Il n'est pas n√©cessaire de comprendre cela pour r√©soudre l'√©nigme propos√©e, mais sachez que si l'on souhaite ne r√©cup√©rer que les informations de certaines colonnes, par exemple `num_permis`, `immatriculation` et `marque`, il suffit de le dire sur la premi√®re ligne. En langue naturelle, on peut l'√©crire ainsi :

<pre><code class="cm-s-ipython language-sql"><span class="cm-keyword">SELECTIONNER</span> num_permis<span class="cm-punctuation">,</span> immatriculation<span class="cm-punctuation">,</span> marque
<span class="cm-keyword">DANS</span> Permis
<span class="cm-keyword">TEL QUE</span> age <span class="cm-operator">=</span> <span class="cm-number">40</span> <span class="cm-keyword">ET</span> genre <span class="cm-operator">=</span> <span class="cm-string">"F"</span>
</code></pre>

Et cela s'√©crit de la mani√®re suivante en SQL :

In [ ]:
SELECT num_permis, immatriculation, marque
FROM Permis
WHERE age = 40 AND genre = "F"

# üîé √ânigme üîé

<div style="background-color: rgba(0, 0, 255, 0.1);padding: 20px;border-radius: 5px;">

Un conducteur a √©t√© surpris en plein d√©lit de fuite apr√®s un accrochage avec un autre conducteur. Deux t√©moins ont assist√© √† la sc√®ne, voici leurs t√©moignages :

- <span style="font-size:1.5em">üó£Ô∏è</span> **T√©moignage n¬∞1** : ¬´ *J'ai bien vu le conducteur car la vitre de sa voiture √©tait baiss√©e. Je ne sais pas comment il s'appelle mais je l'ai d√©j√† vu plusieurs fois car il habite dans la m√™me rue que ma cousine, la rue Lejeune. C'est un homme blond assez jeune, je dirais moins de 30 ans.* ¬ª

- <span style="font-size:1.5em">üó£Ô∏è</span> **T√©moignage n¬∞2** : ¬´ *J'ai vu que la voiture √©tait de la marque Audi mais je n'ai pas eu le temps de noter le num√©ro de la plaque d'immatriculation...* ¬ª

Votre objectif est de trouver le suspect gr√¢ce √† des requ√™tes SQL. Utilisez pour cela les cellules ci-dessous (autant que vous voulez) pour √©crire vos requ√™tes et r√©soudre cette enqu√™te !
    
La r√©ponse √† cette √©nigme est l'identit√© du suspect. *Attention, la r√©ponse doit √™tre donn√©e sous la forme Prenom Nom comme dans la colonne `nom` de la table `Habitants`(exemple : Matthieu Rey)*.
    
</div>

Voici ci-dessous plusieurs cellules o√π vous pouvez √©crire des requ√™tes SQL pour trouver l'identit√© du suspect.

>Il y en a largement assez normalement, mais vous pouvez en ajouter autant que vous le souhaitez en cliquant sur le bouton <button class='fa fa-plus'></button> situ√© dans la barre de menu qui ajoute une cellule en-dessous de celle s√©lectionn√©e.

---

Germain Becker, Lyc√©e Emmanuel Mounier, Angers.

![Licence Creative Commons](https://i.creativecommons.org/l/by-sa/4.0/88x31.png)